"""initial baseline schema

Revision ID: 6661588637cc
Revises:
Create Date: 2026-07-04 20:17:59.818267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6661588637cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=150), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('changes_json', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False, schema='analytics')
    op.create_table('blockers',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('blocked_task_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('reported_by_user_id', sa.UUID(), nullable=False),
    sa.Column('pending_on_user_id', sa.UUID(), nullable=False),
    sa.Column('expected_resolution_date', sa.Date(), nullable=True),
    sa.Column('actual_resolution_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('P0', 'P1', 'P2', 'P3')", name='ck_blocker_priority'),
    sa.CheckConstraint("severity IN ('Low', 'Medium', 'High', 'Critical')", name='ck_blocker_severity'),
    sa.CheckConstraint("status IN ('Open', 'InProgress', 'Resolved', 'Cancelled')", name='ck_blocker_status'),
    sa.PrimaryKeyConstraint('id'),
    schema='blockers'
    )
    op.create_index(op.f('ix_blockers_blockers_blocked_task_id'), 'blockers', ['blocked_task_id'], unique=False, schema='blockers')
    op.create_index(op.f('ix_blockers_blockers_pending_on_user_id'), 'blockers', ['pending_on_user_id'], unique=False, schema='blockers')
    op.create_index(op.f('ix_blockers_blockers_status'), 'blockers', ['status'], unique=False, schema='blockers')
    op.create_table('comments',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('mentioned_user_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['collaboration.comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='collaboration'
    )
    op.create_index(op.f('ix_collaboration_comments_entity_id'), 'comments', ['entity_id'], unique=False, schema='collaboration')
    op.create_index(op.f('ix_collaboration_comments_entity_type'), 'comments', ['entity_type'], unique=False, schema='collaboration')
    op.create_table('file_attachments',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='collaboration'
    )
    op.create_index(op.f('ix_collaboration_file_attachments_entity_id'), 'file_attachments', ['entity_id'], unique=False, schema='collaboration')
    op.create_index(op.f('ix_collaboration_file_attachments_entity_type'), 'file_attachments', ['entity_type'], unique=False, schema='collaboration')
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='collaboration'
    )
    op.create_index(op.f('ix_collaboration_notifications_user_id'), 'notifications', ['user_id'], unique=False, schema='collaboration')
    op.create_table('permissions',
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_permissions_code'),
    schema='identity'
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_roles_name'),
    schema='identity'
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_users_email'), 'users', ['email'], unique=False, schema='identity')
    op.create_table('departments',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('head_of_department_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_departments_name'),
    schema='organization'
    )
    op.create_table('skills',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_skills_name'),
    schema='organization'
    )
    op.create_table('products',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('technology_stack', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('documentation_link', sa.String(length=500), nullable=True),
    sa.Column('environment', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("environment IN ('Development', 'Staging', 'Production')", name='ck_environment'),
    sa.CheckConstraint("priority IN ('P0', 'P1', 'P2', 'P3')", name='ck_priority'),
    sa.CheckConstraint("status IN ('Planning', 'Active', 'Maintenance', 'Sunset')", name='ck_status'),
    sa.PrimaryKeyConstraint('id'),
    schema='projects'
    )
    op.create_table('task_labels',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_task_labels_name'),
    schema='projects'
    )
    op.create_table('reactions',
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['collaboration.comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='collaboration'
    )
    op.create_index(op.f('ix_collaboration_reactions_comment_id'), 'reactions', ['comment_id'], unique=False, schema='collaboration')
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False, schema='identity')
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_ip', sa.String(length=64), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_token_hash', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False, schema='identity')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['identity.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['identity.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='identity'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['identity.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='identity'
    )
    op.create_table('teams',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('lead_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['organization.departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='organization'
    )
    op.create_index(op.f('ix_organization_teams_department_id'), 'teams', ['department_id'], unique=False, schema='organization')
    op.create_table('projects',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('estimated_completion_date', sa.Date(), nullable=True),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('health_status', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("health_status IN ('on-track', 'at-risk', 'delayed', 'blocked', 'completed')", name='ck_health_status'),
    sa.CheckConstraint("priority IN ('P0', 'P1', 'P2', 'P3')", name='ck_priority'),
    sa.CheckConstraint("risk_level IN ('Low', 'Medium', 'High', 'Critical')", name='ck_risk_level'),
    sa.CheckConstraint("status IN ('not-started', 'in-progress', 'on-hold', 'completed', 'cancelled')", name='ck_status'),
    sa.ForeignKeyConstraint(['product_id'], ['projects.products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='projects'
    )
    op.create_index(op.f('ix_projects_projects_product_id'), 'projects', ['product_id'], unique=False, schema='projects')
    op.create_table('employees',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('manager_employee_id', sa.UUID(), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('hire_date', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_employee_id'], ['organization.employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['organization.teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_employees_user_id'),
    schema='organization'
    )
    op.create_index(op.f('ix_organization_employees_team_id'), 'employees', ['team_id'], unique=False, schema='organization')
    op.create_index(op.f('ix_organization_employees_user_id'), 'employees', ['user_id'], unique=False, schema='organization')
    op.create_table('phases',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phase_type', sa.String(length=30), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('lead_assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("phase_type IN ('Requirements', 'Architecture', 'Design', 'Development', 'Testing', 'Deployment', 'Maintenance')", name='ck_phase_type'),
    sa.CheckConstraint("status IN ('not-started', 'in-progress', 'blocked', 'completed', 'delayed')", name='ck_status'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='projects'
    )
    op.create_index(op.f('ix_projects_phases_project_id'), 'phases', ['project_id'], unique=False, schema='projects')
    op.create_table('project_members',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('ProjectManager', 'TeamLead', 'Developer', 'QA', 'UIUX', 'BusinessAnalyst', 'Client', 'Observer')", name='ck_role'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id'),
    schema='projects'
    )
    op.create_table('employee_skills',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('proficiency_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['organization.employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['organization.skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'skill_id'),
    schema='organization'
    )
    op.create_table('phase_team_assignments',
    sa.Column('phase_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['projects.phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('phase_id', 'team_id'),
    schema='projects'
    )
    op.create_table('tasks',
    sa.Column('phase_id', sa.UUID(), nullable=False),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('actual_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('earliest_start', sa.Integer(), nullable=True),
    sa.Column('earliest_finish', sa.Integer(), nullable=True),
    sa.Column('latest_start', sa.Integer(), nullable=True),
    sa.Column('latest_finish', sa.Integer(), nullable=True),
    sa.Column('total_slack', sa.Integer(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('P0', 'P1', 'P2', 'P3')", name='ck_priority'),
    sa.CheckConstraint("status IN ('NotStarted', 'Ready', 'InProgress', 'Waiting', 'Blocked', 'Review', 'Testing', 'Done', 'Cancelled', 'Archived')", name='ck_status'),
    sa.CheckConstraint("task_type IN ('Feature', 'Bug', 'Enhancement', 'Research', 'Documentation', 'Meeting', 'Testing', 'Deployment')", name='ck_task_type'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['projects.tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phase_id'], ['projects.phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='projects'
    )
    op.create_index(op.f('ix_projects_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False, schema='projects')
    op.create_index(op.f('ix_projects_tasks_phase_id'), 'tasks', ['phase_id'], unique=False, schema='projects')
    op.create_table('checklist_items',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['projects.tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='projects'
    )
    op.create_index(op.f('ix_projects_checklist_items_task_id'), 'checklist_items', ['task_id'], unique=False, schema='projects')
    op.create_table('task_assignees',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['projects.tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id'),
    schema='projects'
    )
    op.create_table('task_dependencies',
    sa.Column('predecessor_task_id', sa.UUID(), nullable=False),
    sa.Column('successor_task_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(length=30), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dependency_type IN ('FinishToStart', 'StartToStart', 'FinishToFinish', 'StartToFinish')", name='ck_dependency_type'),
    sa.ForeignKeyConstraint(['predecessor_task_id'], ['projects.tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_task_id'], ['projects.tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('predecessor_task_id', 'successor_task_id', name='uq_task_dependency_pair'),
    schema='projects'
    )
    op.create_index(op.f('ix_projects_task_dependencies_predecessor_task_id'), 'task_dependencies', ['predecessor_task_id'], unique=False, schema='projects')
    op.create_index(op.f('ix_projects_task_dependencies_successor_task_id'), 'task_dependencies', ['successor_task_id'], unique=False, schema='projects')
    op.create_table('task_label_assignments',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['projects.task_labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['projects.tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'label_id'),
    schema='projects'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_label_assignments', schema='projects')
    op.drop_index(op.f('ix_projects_task_dependencies_successor_task_id'), table_name='task_dependencies', schema='projects')
    op.drop_index(op.f('ix_projects_task_dependencies_predecessor_task_id'), table_name='task_dependencies', schema='projects')
    op.drop_table('task_dependencies', schema='projects')
    op.drop_table('task_assignees', schema='projects')
    op.drop_index(op.f('ix_projects_checklist_items_task_id'), table_name='checklist_items', schema='projects')
    op.drop_table('checklist_items', schema='projects')
    op.drop_index(op.f('ix_projects_tasks_phase_id'), table_name='tasks', schema='projects')
    op.drop_index(op.f('ix_projects_tasks_parent_task_id'), table_name='tasks', schema='projects')
    op.drop_table('tasks', schema='projects')
    op.drop_table('phase_team_assignments', schema='projects')
    op.drop_table('employee_skills', schema='organization')
    op.drop_table('project_members', schema='projects')
    op.drop_index(op.f('ix_projects_phases_project_id'), table_name='phases', schema='projects')
    op.drop_table('phases', schema='projects')
    op.drop_index(op.f('ix_organization_employees_user_id'), table_name='employees', schema='organization')
    op.drop_index(op.f('ix_organization_employees_team_id'), table_name='employees', schema='organization')
    op.drop_table('employees', schema='organization')
    op.drop_index(op.f('ix_projects_projects_product_id'), table_name='projects', schema='projects')
    op.drop_table('projects', schema='projects')
    op.drop_index(op.f('ix_organization_teams_department_id'), table_name='teams', schema='organization')
    op.drop_table('teams', schema='organization')
    op.drop_table('user_roles', schema='identity')
    op.drop_table('role_permissions', schema='identity')
    op.drop_index(op.f('ix_identity_refresh_tokens_user_id'), table_name='refresh_tokens', schema='identity')
    op.drop_index(op.f('ix_identity_refresh_tokens_token_hash'), table_name='refresh_tokens', schema='identity')
    op.drop_table('refresh_tokens', schema='identity')
    op.drop_index(op.f('ix_identity_password_reset_tokens_user_id'), table_name='password_reset_tokens', schema='identity')
    op.drop_index(op.f('ix_identity_password_reset_tokens_token_hash'), table_name='password_reset_tokens', schema='identity')
    op.drop_table('password_reset_tokens', schema='identity')
    op.drop_index(op.f('ix_collaboration_reactions_comment_id'), table_name='reactions', schema='collaboration')
    op.drop_table('reactions', schema='collaboration')
    op.drop_table('task_labels', schema='projects')
    op.drop_table('products', schema='projects')
    op.drop_table('skills', schema='organization')
    op.drop_table('departments', schema='organization')
    op.drop_index(op.f('ix_identity_users_email'), table_name='users', schema='identity')
    op.drop_table('users', schema='identity')
    op.drop_table('roles', schema='identity')
    op.drop_table('permissions', schema='identity')
    op.drop_index(op.f('ix_collaboration_notifications_user_id'), table_name='notifications', schema='collaboration')
    op.drop_table('notifications', schema='collaboration')
    op.drop_index(op.f('ix_collaboration_file_attachments_entity_type'), table_name='file_attachments', schema='collaboration')
    op.drop_index(op.f('ix_collaboration_file_attachments_entity_id'), table_name='file_attachments', schema='collaboration')
    op.drop_table('file_attachments', schema='collaboration')
    op.drop_index(op.f('ix_collaboration_comments_entity_type'), table_name='comments', schema='collaboration')
    op.drop_index(op.f('ix_collaboration_comments_entity_id'), table_name='comments', schema='collaboration')
    op.drop_table('comments', schema='collaboration')
    op.drop_index(op.f('ix_blockers_blockers_status'), table_name='blockers', schema='blockers')
    op.drop_index(op.f('ix_blockers_blockers_pending_on_user_id'), table_name='blockers', schema='blockers')
    op.drop_index(op.f('ix_blockers_blockers_blocked_task_id'), table_name='blockers', schema='blockers')
    op.drop_table('blockers', schema='blockers')
    op.drop_index(op.f('ix_analytics_audit_logs_user_id'), table_name='audit_logs', schema='analytics')
    op.drop_index(op.f('ix_analytics_audit_logs_entity_type'), table_name='audit_logs', schema='analytics')
    op.drop_index(op.f('ix_analytics_audit_logs_entity_id'), table_name='audit_logs', schema='analytics')
    op.drop_table('audit_logs', schema='analytics')
    # ### end Alembic commands ###
