import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight, CirclePlay } from "lucide-react";
import { PublicDocsLayout } from "@/components/docs/PublicDocsLayout";
import { PUBLIC_DOCS, findDoc } from "@/lib/docs/content";
import { getPublishedDoc } from "@/lib/docs/server";
export function generateStaticParams(){return PUBLIC_DOCS.map(({category,slug})=>({category,slug}))}
export async function generateMetadata({params}:{params:Promise<{category:string;slug:string}>}):Promise<Metadata>{const {category,slug}=await params;const doc=findDoc(category,slug)??await getPublishedDoc(category,slug);return doc?{title:doc.title,description:doc.description,alternates:{canonical:`/docs/${category}/${slug}`},openGraph:{title:doc.title,description:doc.description,type:"article"}}:{}}
export default async function DocArticle({params}:{params:Promise<{category:string;slug:string}>}){const {category,slug}=await params;const local=findDoc(category,slug);const doc=local??await getPublishedDoc(category,slug);if(!doc)notFound();const index=local?PUBLIC_DOCS.indexOf(local):-1;const previous=index>0?PUBLIC_DOCS[index-1]:undefined;const next=index>=0?PUBLIC_DOCS[index+1]:undefined;return <PublicDocsLayout currentCategory={category} currentSlug={slug} toc={doc.sections.map(({id,title})=>({id,title}))}><article className="docs-article"><div className="docs-article-meta"><span>{doc.categoryLabel}</span><span>Updated August 2026</span></div><h1>{doc.title}</h1><p className="docs-lead">{doc.description}</p>{doc.videoId&&<div className="docs-video"><div><CirclePlay size={40}/><span>Video tutorial</span><b>{doc.title}</b></div><p>The written guide remains available below. Video loads only when you choose to watch.</p><a href={`https://www.youtube.com/watch?v=${doc.videoId}`} target="_blank" rel="noreferrer">Watch on YouTube <ArrowRight size={15}/></a></div>}{doc.sections.map((section)=><section id={section.id} key={section.id}><h2>{section.title}</h2><p>{section.body}</p>{section.steps&&<ol>{section.steps.map(step=><li key={step}>{step}</li>)}</ol>}</section>)}<div className="docs-feedback"><div><b>Was this guide useful?</b><span>Feedback helps keep documentation clear.</span></div><button type="button">Yes</button><button type="button">Not yet</button></div><nav className="docs-pager" aria-label="Previous and next guides">{previous?<Link href={`/docs/${previous.category}/${previous.slug}`}><ArrowLeft size={16}/><span><small>Previous</small>{previous.title}</span></Link>:<span/>}{next&&<Link href={`/docs/${next.category}/${next.slug}`}><span><small>Next</small>{next.title}</span><ArrowRight size={16}/></Link>}</nav></article></PublicDocsLayout>}
