"use client";
import { Suspense, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { KeyRound } from "lucide-react";
import { AccessShell } from "@/components/ui/AccessShell";
import { Button, Field, TextInput } from "@/components/ds";
import { resetPassword } from "@/lib/api/auth";
function ResetForm(){const params=useSearchParams();const token=params.get("token")??"";const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [status,setStatus]=useState<"idle"|"loading"|"done"|"error">("idle");const mismatch=!!confirm&&password!==confirm;async function submit(event:React.FormEvent){event.preventDefault();if(mismatch||password.length<8||!token)return;setStatus("loading");try{await resetPassword(token,password);setStatus("done")}catch{setStatus("error")}}if(!token)return <div className="pmp-access-error" role="alert">This reset link is incomplete or expired. <Link href="/forgot-password">Request a new link.</Link></div>;if(status==="done")return <div className="pmp-access-success" role="status"><h2>Password updated</h2><p>You can now sign in with your new password.</p><Link href="/login">Continue to login</Link></div>;return <form className="pmp-access-form" onSubmit={submit}><Field label="New password"><TextInput type="password" autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)}/></Field><Field label="Confirm password"><TextInput type="password" autoComplete="new-password" value={confirm} onChange={event=>setConfirm(event.target.value)}/></Field>{mismatch&&<div className="pmp-access-error" role="alert">Passwords do not match.</div>}{status==="error"&&<div className="pmp-access-error" role="alert">The password could not be reset. Request a new link and try again.</div>}<Button type="submit" disabled={status==="loading"||password.length<8||mismatch}><KeyRound size={16}/>{status==="loading"?"Updating…":"Update password"}</Button></form>}
export default function ResetPasswordPage(){return <AccessShell eyebrow="Account recovery" title="Choose a new password" description="Use at least eight characters and avoid reusing an old password."><Suspense fallback={<div>Loading reset form…</div>}><ResetForm/></Suspense></AccessShell>}
